#!/bin/sh

DAEMON=/usr/bin/mot.py
PIDFILE=/var/run/mot.pid
STATEFILE=/var/cache/mot.state
DESC="Master of Things daemon"

set -e

do_start() {
	ARGS="-p $PIDFILE"
	test -r $STATEFILE || ARGS="$ARGS -r"
	start-stop-daemon --start --background --pidfile $PIDFILE --quiet $DAEMON -- $ARGS
}

do_stop() {
	start-stop-daemon --stop --quiet --pidfile $PIDFILE
}

case "$1" in
  start)
	echo "Starting $DESC"
	do_start
	;;
  stop)
	echo "Stopping $DESC"
	do_stop
	;;
  restart|force-reload)
	echo "Restarting $DESC"
	do_stop
	sleep 1
	do_start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
